### ISSUE TITLE
Clarification 

### ISSUE THREAD

**Issue by carstenbauer** [juliohm/julia-distributed-computing#4]
I think it would be appropriate if it was mentioned at the top of the readme that this is the "ultimate guide for distributed computing with Julia" **using Distributed.jl**. As it stands, it is at least misleading because MPI - the worldwide de facto standard for distributed computing - isn't even mentioned.

**Comment by juliohm** [comment]
Good point. Can you submit a PR that mentions Distributed and other alternatives (e.g. Dagger.jl, MPI.jl)?

**Comment by carstenbauer** [comment]
I made a simple PR. Note that Dagger.jl doesn't necessarily need to be mentioned because it almost entirely builds upon Distributed.jl as well. (It could be linked of course but that's not what this issue is about.)
